### ISSUE TITLE
UserMapper::class 

### ISSUE THREAD

**Issue by Gamewalker** [Saeven/zf3-circlical-user#11]
Hey, I tried implement this module via doctrine and the database and stuff got generated nicely but if I activate the module, it isnt working. What am I doing wrong?

![unbenannt](https://cloud.githubusercontent.com/assets/241821/19815247/464d4366-9d42-11e6-818e-b4b863539fc2.PNG)

**Comment by Saeven** [comment]
Looks like an error related to guards.  You add guards into your module config?  In the README, the relevant config section is this one

```
 return [
    'circlical' => [
        'user' => [
            'guards' => [
                'ModuleName' => [
                    \Application\Controller\IndexController::class => [
                        'default' => [], // anyone can access
                    ],
                    \Application\Controller\MemberController::class => [
                        'default' => ['user'], // specific role access
                    ],
                    \Application\Controller\AdminController::class => [
                        'default' => ['admin'],
                        'actions' => [  // action-level guards
                            'list' => [ 'user' ], // role 'user' can access 'listAction' on AdminController
                        ],
                    ],
                ],
            ],
        ],
    ],
 ];
```

**Comment by Saeven** [comment]
I'm at work right now, but I'll try to add a trap for that. Thanks for flagging it.

**Comment by Gamewalker** [comment]
damn it, I started with the doctrine page and never came back to the readme part :)

**Comment by Gamewalker** [comment]
Should it really be necessary to configure every module and every controller inside? 
What about a config entry to set a default behaviour?

**Comment by Saeven** [comment]
I guess it was a design decision to make it 'deny first'.  I can make it 'deny' if there's no config.  I'll add tests and pull tonight.

**Comment by Gamewalker** [comment]
Feeling like a complete idiot, I added: 

``` php
    'circlical' => [
        'user' => [
            'guards' => [
                __NAMESPACE__ => [
                    \Capacity\Controller\CapacityController::class => [
                        'default' => [], // anyone can access
                    ],
                    \Capacity\Controller\ServiceController::class => [
                        'default' => [], // anyone can access
                    ],
                ],
                "Capacity" => [
                    \Capacity\Controller\CapacityController::class => [
                        'default' => [], // anyone can access
                    ],
                    \Capacity\Controller\ServiceController::class => [
                        'default' => [], // anyone can access
                    ],
                ],
            ],
        ],
    ],
```

and neither of this is working and throwing: 
```php
Fatal error: Uncaught CirclicalUser\Exception\GuardExpectedException: No rules are configured for guard Capacity\Controller\CapacityController. in /var/www/vendor/saeven/zf3-circlical-user/src/CirclicalUser/Service/AccessService.php on line 194
```

If I debug output AccessService there is this:
```php
/var/www/vendor/zendframework/zend-debug/src/Debug.php:97:
array (size=2)
  'Capacity\Controller\CapacityController' => 
    array (size=1)
      'default' => 
        array (size=0)
          empty
  'Capacity\Controller\ServiceController' => 
    array (size=1)
      'default' => 
        array (size=0)
          empty
```

**Comment by Gamewalker** [comment]
seems like the syntax was wrong, should be:

```php
    'circlical' => [
        'user' => [
            'guards' => [
                __NAMESPACE__ => [
                    "controllers" => [
                        \Capacity\Controller\CapacityController::class => [
                            'default' => [], // anyone can access
                        ],
                        \Capacity\Controller\ServiceController::class => [
                            'default' => [], // anyone can access
                        ],
                    ]
                ],
            ],
        ],
    ],
```

**Comment by Saeven** [comment]
Here's a sample from a working app:

In my module config I have:

    'circlical' => [
        'user' => [
            'guards' => require 'guards.config.php',
        ],
     ],

Then, the guards.config.php looks like:

    return [
        'Application' => [
            'controllers' => [
                \Application\Controller\IndexController::class => ['default' => [],],
                \Application\Controller\LoginController::class => ['default' => [],],
                \Application\Controller\DomainController::class => ['default' => [],],
                \Application\Controller\CheckoutController::class => ['default' => [],],
                \Application\Controller\RegisterController::class => ['default' => [],],
                \Application\Controller\InvoiceController::class => ['default' => ['user']],
                \DoctrineORMModule\Yuml\YumlController::class => ['default' => []],
            ],
        ],
    ];

**Comment by Saeven** [comment]
You can see the tests here if it helps
https://github.com/Saeven/zf3-circlical-user/blob/master/bundle/Spec/CirclicalUser/Service/AccessServiceSpec.php#L132

**Comment by Gamewalker** [comment]
All fine now, thx
