### ISSUE TITLE
Default rule for development modules?

### ISSUE THREAD

**Issue by Gamewalker** [Saeven/zf3-circlical-user#18]
Hello, if you enable the dev toolbar you can generate a yuml dependency graph but this calls the YumlController class and this isnt allowed by default. Should this be added by default?

**Comment by Koopzington** [comment]
BjyAuthorize didn't have such a thing and i think it's not a good idea either.
We shouldn't "open up" the system just for having it easier in development stage.

**Comment by Saeven** [comment]
I agree, I think the onus should be on the developer to add in their dependencies based on where they are pinned.  If we agree to let something "like this" in, we agree to maintain it over its life.  I think that's a burden best left untouched.

**Comment by Gamewalker** [comment]
ok, I agree. close
