### ISSUE TITLE
undefined AuthenticationService::registerAuthenticationRecord()

### ISSUE THREAD

**Issue by CreativeNative** [Saeven/zf3-circlical-user#20]
[create-only](https://github.com/Saeven/zf3-circlical-user#create-only)

Call to undefined method CirclicalUser\Service\AuthenticationService::registerAuthenticationRecord()

I saw the [PR16](https://github.com/Saeven/zf3-circlical-user/pull/16), so now I'm little bit confused. Could you please update the Documentation.

**Comment by Gamewalker** [comment]
PR16 is already implemented by his own code. Are you using the actual code? I implemented a user controller yesterday and used the new function already.

**Comment by Saeven** [comment]
@CreativeNative Make sure you are using dev-master to get that function.  I am working on adding a 'forgot password' link generator, and will tag a release at that point.
