### ISSUE TITLE
Create new user

### ISSUE THREAD

**Issue by buchmayr** [Saeven/zf3-circlical-user#22]
I use following method in controller:
`    public function registerAction()
    {
        $user = new User();
        $form = new RegisterForm($this->em);
        $form->bind($user);
        if ($this->getRequest()->isPost()) {
            $form->setData($this->getRequest()->getPost());
            if ($form->isValid()) {
                $this->auth()->create($user, $user->getName(), $user->getPassword());
            }
        }
        return new ViewModel(array('form' => $form));
    }`

but if I add a user object with id = NULL, I get the following error

> CirclicalUser\Exception\PersistedUserRequiredException

File:

    C:\xampp\htdocs\zf3\vendor\saeven\zf3-circlical-user\src\CirclicalUser\Service\AuthenticationService.php:475

Message:

    Your user must have an ID before you can create auth records with it

**Comment by buchmayr** [comment]
sorry, I forgot to persists the user first. I thought the plugin will check the uniqueness of the user first....

**Comment by bluebaroncanada** [comment]
I'm a bit confused with this, too.  So we're supposed to create the user ourselves?  Like ... how do we set the password and such?  Should I be adding password to my entity?  I thought you were providing the encryption for it.

**Comment by Saeven** [comment]
Users are such a critical domain object, I didn't want this library to infringe on how it is crafted.  I remember with ZFCUser we had to create event taps for everything that had to do with reg forms, login pages, etc.  It was not ideal, in my opinion.  One of the main goals of this library was to return the user and the user-gen forms to you.  I think it panned out well, I've seen some integrations of circlical-user where folks have used multiple user object types very cleverly in concert.

If you click on the Wiki tab above, you will see there is a sample Reg and Login page controller.  It's very trivial to program.

**Comment by bluebaroncanada** [comment]
omg.  There's a wiki.  This was my second crack at this and it took hours.  I actually got logins working last night.

**Comment by Saeven** [comment]
Sorry to hear it was a rough go!  Feel free to contribute to the wiki if you hit any pain points you feel might help others!  The tests are also a great help during the more complex integrations.

**Comment by bluebaroncanada** [comment]
Would like to know how to implement the addRole, getRoles.  Just add to the ArrayCollection?  I'm guessing that means I should also have an ArrayCollection?  and you handle the rest of that?

**Comment by Saeven** [comment]
You just need to add the roles to your acl_roles database.  An example setup could be these two tuples:

{id:1, parent_id:null, name:user},
{id:2, parent_id:1, name:admin}

Your user entity will give you the means to create relationships for roles:
https://github.com/Saeven/zf3-circlical-user/blob/master/src/CirclicalUser/Entity/User.php.sample#L133

All you need to do, is add the Role for the user, and persist the user:
https://github.com/Saeven/zf3-circlical-user/blob/master/src/CirclicalUser/Entity/User.php.sample#L233

The access service gives you all the convenience methods you need to manage and get roles themselves.  Check out the role-related tests here:

https://github.com/Saeven/zf3-circlical-user/blob/master/bundle/Spec/CirclicalUser/Service/AccessServiceSpec.php#L258
