### ISSUE TITLE
Creating user withouth logging them in

### ISSUE THREAD

**Issue by vojtabiberle** [Saeven/zf3-circlical-user#24]
When I use in controller `$this->auth()->create($user, $username, $password)` `AuthenticationService` automaticly log this new user in. But what if I'm already logged in (for example as administrator) and I only want create new user?

Should be here new method or special parameter of method `create`? Or should I use `AuthenticationService->registerAuthenticationRecord()` directly?

PS: This is design&architecture question.

**Comment by Saeven** [comment]
Hi!  Yes, in an effort to pokayoke the controller plugin, it's necessary to use the Authentication service directly when using the system from an 'admin' capacity.
