### ISSUE TITLE
Disable for module

### ISSUE THREAD

**Issue by drchav** [Saeven/zf3-circlical-user#25]
There is anyway that I can Disable the guard for a entire module?

**Comment by Saeven** [comment]
Hi!  Because it's so quick to configure, and so important to configure just the same - I recommend via implementation, foregoing any special exception mechanisms that could lead to trouble down the road.  This is the stuff of breaches, in my opinion, but I am a paranoid fellow! :)

It also ensures a single way of doing things - which is important. 

In this module, the full controller name is truly the key that controls guards.

**Comment by drchav** [comment]
The problem is as I'm using some apigility things in this project, I only need the APIs to be totally exposed and I'm having some difficulties to implement the guards with apigility routes.

**Comment by Saeven** [comment]
I've admittedly never tried using them in concert.  Defining the rules for the Apigility controller that handles the request, doesn't work?

**Comment by drchav** [comment]
No I got always the same error:
Fatal error: Uncaught TypeError: Argument 2 passed to CirclicalUser\Service\AccessService::requiresAuthentication() must be of the type string, null given, called in /Users/danielchaves/Rocket/TagRocket/System/vendor/saeven/zf3-circlical-user/src/CirclicalUser/Listener/AccessListener.php on line 52 and defined in /Users/danielchaves/Rocket/TagRocket/System/vendor/saeven/zf3-circlical-user/src/CirclicalUser/Service/AccessService.php on line

and I have this on the module config:

  'circlical' => [
        'user' => [
            'guards' => [
                'ModuleName' => [
                    "controllers" => [
                        \TagRocketAPI\V1\Rest\Beacons\BeaconsResource::class  => [
                            'default' => [''],
                        ],
                    ],

                ],
            ],
        ],

**Comment by Saeven** [comment]
Those are drawn from the route's controller and action names.

https://github.com/Saeven/zf3-circlical-user/blob/master/src/CirclicalUser/Listener/AccessListener.php#L52

Possible that Apigility does not pass these?

**Comment by drchav** [comment]
Apigility do not pass a action just the controller, I will adapt this module to my needs thanks for your help.

**Comment by Saeven** [comment]
I could easily rig something that relies on a "Controller" default rather than Module default.

**Comment by Saeven** [comment]
@drchav with zend-mvc's recent support for middleware definitions, I'd like to add this in.  Were you using this with Expressive?
