### ISSUE TITLE
Can't install with composer

### ISSUE THREAD

**Issue by diego-spacecode** [Saeven/zf3-circlical-user#3]
Hi I'm trying to install on a ZF3 skeleton application, but I get dependency issues with zend-servicemanager.

Steps to reproduce:

$ composer create-project --stability="dev" zendframework/skeleton-application /path/to/install
$ composer require saeven/zf3-circlical-user

Is there any workaround for this?
Thanks!

**Comment by Saeven** [comment]
Hey Diego!

Can you paste the output you're getting?

Thanks!

**Comment by diego-spacecode** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for saeven/zf3-circlical-user ^0.1.5 -> satisfiable by saeven/zf3-circlical-user[0.1.5].
    - Conclusion: remove zendframework/zend-servicemanager 3.1.0
    - Conclusion: don't install zendframework/zend-servicemanager 3.1.0
    - saeven/zf3-circlical-user 0.1.5 requires zendframework/zend-servicemanager ^2.7.6 -> satisfiable by zendframework/zend-servicemanager[2.7.6, 2.7.7].
    - Can only install one of: zendframework/zend-servicemanager[2.7.6, 3.1.0].
    - Can only install one of: zendframework/zend-servicemanager[2.7.7, 3.1.0].
    - Installation request for zendframework/zend-servicemanager (locked at 3.1.0) -> satisfiable by zendframework/zend-servicemanager[3.1.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by Saeven** [comment]
Oh I see.  I hadn't yet upgraded this package to work with the new SM.  I can do it though.  I was waiting for DoctrineModule to release support for zend-mvc 3 to do it all in one shot.

**Comment by Saeven** [comment]
I put some work in last night to do the factory work.  It should be usable, tests pass!  I want to add a few more tests tonight, and then I'll press a release that's zend-mvc 3 ready.

**Comment by Saeven** [comment]
(on dev-master)

**Comment by diego-spacecode** [comment]
Great, Thanks!

**Comment by Saeven** [comment]
Let me know if things panned out, I'll close this issue ;)

**Comment by diego-spacecode** [comment]
Yes, perfectly. Thanks!

**Comment by Saeven** [comment]
Alright great!
