### ISSUE TITLE
Unauthorized strategy

### ISSUE THREAD

**Issue by kersten** [Saeven/zf3-circlical-user#6]
Hi,

how would I integrate an unauthorized strategy for all modules in my Main module?

thx

Kersten

**Comment by Saeven** [comment]
I wanted to stay away from complexity in this regard, so currently, it simply shows your user/403 and sends a 403 status code.

```
public function onDispatchError(MvcEvent $event)
    {
        switch ($event->getError()) {

            case AccessService::ACCESS_DENIED:

                if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
                    $viewModel = new JsonModel();
                } else {
                    $viewModel = new ViewModel();
                    $viewModel->setTemplate('user/403');
                }


                $viewModel->setVariables($event->getParams());

                $response = $event->getResponse() ?: new Response();
                $response->setStatusCode(403);
                $event->setViewModel($viewModel);
                $event->setResponse($response);
                break;
            default:
                // do nothing if this is a different kind of error we should not trap
                return;
        }
    }
``

What did you have in mind?

Cheers!
Alex

**Comment by kersten** [comment]
Ok, thanks for the hint. But there should be a difference between access denied and not logged in.

There should be a `AccessService::UNAUTHORIZED` or something.

**Comment by Saeven** [comment]
Fair.  I'll tweak that right away - lunchtime hot fix.

**Comment by Saeven** [comment]
https://github.com/Saeven/zf3-circlical-user/pull/8

**Comment by Saeven** [comment]
I've built in a means to differentiate things. In your app, how do you plan to handle a 403/401?  Maybe I can make things simpler than just asking devs to trap the status code..

**Comment by kersten** [comment]
Thanks.

I want to redirect 401 users to a login page and 403 users to a access denied page, that's all.

If u plan to integrate it in your module, it would be nice to see it configurable. Maybe something like this:

```php
[
	'circlical' => [
		'unauthorized' => [
			'type' => Redirect::class,

			'options' => [
				'route'    => '/login',
			],
		],
	],
]
```

**Comment by Saeven** [comment]
Coded something up at lunch today, that I later checked in.  Give it a shot! Tagged release 2.0.

**Comment by kersten** [comment]
Many thanks. But I have some concerns about your `RedirectStrategy`. It is not really redirecting it just sets the route to the defined route. That could be a problem, as in my case the layout is a different one for the login route than for the requested one.

What do you think of something like this?

```php
<?php

namespace CirclicalUser\Strategy;

use CirclicalUser\Provider\DenyStrategyInterface;
use CirclicalUser\Service\AccessService;
use Zend\Mvc\MvcEvent;
use Zend\Router\RouteMatch;

/**
 * Class RedirectStrategy
 *
 * @package CirclicalUser\Strategy
 *
 * Show the user to a login form if the request is not an XHTTP request, and the gate occurs because no user is
 * logged in.  Do not interject if they are logged in, yet don't have necessary rights.
 */
class RedirectStrategy implements DenyStrategyInterface
{
	/**
	 * The controller that dispatch should invoke
	 *
	 * @var string
	 */
	private $controllerClass;

	/**
	 * This ^ controller's action
	 *
	 * @var string
	 */
	private $action;

	public function __construct( string $controllerClass, string $action )
	{
		$this->controllerClass = $controllerClass;
		$this->action          = $action;
	}

	public function handle( MvcEvent $event, string $eventError ): bool
	{
		if ( $eventError == AccessService::ACCESS_UNAUTHORIZED && empty( $_SERVER[ 'HTTP_X_REQUESTED_WITH' ] ) ) {
			$url      = $event->getRouter()->assemble( [], [ 'name' => 'login' ] );
			$response = $event->getResponse();
			$response->getHeaders()->addHeaderLine( 'Location', $url );
			$response->setStatusCode( 302 );
			$response->sendHeaders();

			$stopCallBack = function ( $event ) use ( $response ) {
				$event->stopPropagation();

				return $response;
			};

			$event->getApplication()->getEventManager()->attach( MvcEvent::EVENT_ROUTE, $stopCallBack, -10000 );

			return $response;
		}

		return FALSE;
	}

}
```

**Comment by Saeven** [comment]
Hey @kersten 

I always go to great lengths to avoid redirects; I use this module for situations where we get 40k user bursts in 1 minute.  Halving the hits is always pretty important.

You should still be able to set layout on dispatch, since this route change occurs at the routing stage.

This type of approach would permit you to set layout based on module:
https://github.com/EvanDotPro/EdpModuleLayouts

I use a similar approach to set layout based on Controller or Module:

 
    $eventManager->getSharedManager()->attach('Zend\Mvc\Controller\AbstractController', 'dispatch', function ($e) {
            $controller = $e->getTarget();
            $controllerClass = get_class($controller);
            $moduleNamespace = substr($controllerClass, 0, strpos($controllerClass, '\\'));
            $config = $e->getApplication()->getServiceManager()->get('config');

            if (isset($config['module_layouts']['controllers'][$controllerClass])) {
                $controller->layout(
                    $config['module_layouts']['controllers'][$controllerClass]
                );
            } else {
                if (isset($config['module_layouts']['modules'][$moduleNamespace])) {
                    $controller->layout($config['module_layouts']['modules'][$moduleNamespace]);
                }
            }
        }, 100);


Then in each module, drop a simple config:

    'module_layouts' => [
        'controllers' => [
            ThisModule\FooController::class => 'layout/member',
        ],
    ],


You can achieve per module, or per controller layout without doubling up on web server hits.

**Comment by Saeven** [comment]
Sorry I forgot to note, you can completely ignore the module-provided redirect, and specify your own as well!  That way, you can espouse any behavior you need.  Please do close this issue at your discretion

**Comment by Saeven** [comment]
@kersten just checking in! Worked out ok?
