### ISSUE TITLE
update composer for doctrine/doctrine-orm-module ^4.0.1

### ISSUE THREAD

**Issue by CreativeNative** [Saeven/zf3-circlical-user#76]
Hi @Saeven, 

I tried to initiate my migration to your really cool module. For that, please update your composer to the latest doctrine-orm-module 4.0.1. I would really appreciate it.

- Root composer.json requires saeven/zf3-circlical-user ^0.2.7 -> satisfiable by saeven/zf3-circlical-user[0.2.7].
- saeven/zf3-circlical-user 0.2.7 requires doctrine/doctrine-orm-module ^1.1||2.1.* -> found doctrine/doctrine-orm-module[1.1.0, ..., 1.1.8, 2.1.0, ..., 2.1.7] but it conflicts with your root composer.json require (^4.0.1).

**Comment by Saeven** [comment]
Hi @CreativeNative!

If you switch over to dev-master, you should be able to install Doctrine 4. We're currently in the midst of migrating from ZF3 to Laminas, and have been doing this with success on dev-master.   Once all the details are ironed out, I'll mint a release version.  Let me know if you're still stuck!

**Comment by CreativeNative** [comment]
Hi @Saeven, thanks for your message. It works, but now I have a problem with the laminas cache, because you replace all cache storage adapters, which I think is right, but actually I haven't updated yet, because the documentation of laminas cache is a real mess. I don't understand how I can use APCu without the adapter, but I will figure it out. Until then, I will postpone the migration.

**Comment by Saeven** [comment]
Yeah, I found it weird that the laminas/cache developers forced us to replace this, rather than relying on opt-in with suggestions.
