### ISSUE TITLE
Upgrade to Laminas Cache ^3.1.2 or delete the requirement

### ISSUE THREAD

**Issue by CreativeNative** [Saeven/zf3-circlical-user#93]
I will try it in my eco system and will send an PR if everything works fine.

**Comment by CreativeNative** [comment]
I don't get it. There is almost no documentation for these new caches. I installed the following packages, but didn't get it managed to configure a running system with for example the filesystem cache. Do you have an idea? 

```
    "laminas/laminas-cache": "^3.1.2",
    "laminas/laminas-cache-storage-adapter-filesystem": "^2.0.0",
```

**Comment by CreativeNative** [comment]
I checked the code. From my point of view it can be deleted. Please check and tell me what do you think.

**Comment by Saeven** [comment]
Will give this a go.  I remember when I last messed with it, laminas-cache was a giant mess.  Things do seem to have improved, despite it being a clunky install still.  I'll create a PR to prepare for 8.1, and also, to recommend putting the replace blocks in the parent composer.
