### ISSUE TITLE
Database contains identifiers that are reserved

### ISSUE THREAD

**Issue by CreativeNative** [Saeven/zf3-circlical-user#94]
` vendor/bin/doctrine-module dbal:reserved-words`     

Checks if the current database contains identifiers that are reserved. 

- Table users_atoms column key keyword violations: DB2, MariaDb102, MySQL, MySQL57, MySQL80, SQLite, SQLServer
- Table users_atoms column value keyword violations: DB2
- Table users_auth column hash keyword violations: DB2

Reminder for changing the users_atoms column key.

**Comment by Saeven** [comment]
You'll notice the 'name' spec in the columns.  I had to do this to retrofit to an existing project framework on my end.  With the names specific, it works just fine (can attest to proper prod behavior on Mysql 5.7 and 8.0)

**Comment by CreativeNative** [comment]
I just stumbled across it and wanted to show it to you.
